#!/usr/bin/env bash
#this script displays numbers from 1 to 100.
cpt=0
while [ $cpt -lt 100 ]
do 
	((cpt++))
	if ! ((cpt%3)) && ! ((cpt%5))
	then
		echo FizzBuzz
	elif ! ((cpt%3))
	then
		echo Fizz
	elif ! ((cpt%5))
	then 
		echo Buzz
	else
		echo $cpt
	fi
done
