#!/usr/bin/env bash
#This while loop from 1 to 10:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations 
cpt=1
while [ $cpt -le 10 ]
do
	if [ $cpt = 4 ]
	then
		echo "bad luck"
    	elif [ $cpt = 8 ]
    	then
        	echo "good luck"
    	else
        	echo "Holberton School"
    	fi
    		((cpt++))
done
