#!/usr/bin/env bash
#this while loop displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
h=0
while [ $h -le 13 ]
do
	echo Hour: $h
	m=0
	while [ $m -lt 60 ]
	do
		echo $m
		((m++))
	done
		((h++))
done
