#!/usr/bin/env bash
#this while loop displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
h=0
while [ $h -le 12 ]
do
	m=0
	echo Hour: $h
	while [ $m -lt 59 ]
	do
		((m++))
		echo $m
	done
		((h++))
done
